name: bill_app
description: 金豆夹

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.1
  path_provider: ^2.1.1
  analyzer: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.7
  share_plus: ^11.0.0 # 用于文件分享
  open_file: ^3.3.1  # 用于打开文件/目录
  url_launcher: ^6.3.1
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/gold_pod.svg  # 声明PNG资源（路径需与项目实际一致）

flutter_launcher_icons:
  android: "launcher_icon"  # Android图标配置
  image_path: "assets/icon/gold_pod.png"  # 源图标路径
version: 0.1.1+1