name: bill_app
description: 黄金交易助手

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.1 
  path_provider: ^2.1.1
  analyzer: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/account_balance_wallet.png" # 你的图标路径
  android: true
  ios: true
  remove_alpha_ios: true # iOS去除透明背景

version: 1.0.0+1