name: bill_app
description: 黄金交易助手

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2  # 最新稳定版[7](@ref)
  intl: ^0.19.0      # 当前版本仍兼容[6,8](@ref)
  shared_preferences: ^2.3.3  # 最新版[15](@ref)
  hive: ^2.2.3       # 当前版本仍兼容[21](@ref)
  hive_flutter: ^1.1.0  # 当前版本仍兼容[21](@ref)
  flutter_secure_storage: ^9.2.4  # 最新版[23,25](@ref)
  encrypt: ^5.0.1    # 当前版本仍兼容[27](@ref)
  path_provider: ^2.1.1  # 最新稳定版[1](@ref)
  analyzer: ^6.0.0   # 当前版本仍兼容[1](@ref)
  hive_generator: ^2.0.1  # 需与hive版本匹配[21](@ref)
  build_runner: ^2.4.15  # 当前版本仍兼容[37,38](@ref)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true